include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/**.gr.dart

linter:
  rules:
    sort_pub_dependencies: false
