name: enhanced_paginated_view
description: the enhanced paginated list view is one of a kind list widget that support pagination
version: 1.0.2
homepage: https://github.com/Mustafa7Ibrahim/enhanced_paginated_view.git

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
